volumio/docs

docs/_index.md

correct link for plugin page

---

docs/03_Plugin_System/03_Index.js.md

I am developing my first plugin and I struggled with the JSON structure that needs to be returned by the search function. I think it is a good idea to mention the expected structure in the documentation.

added expected json response structure when search is called

---

docs/01_Development_How_To/02_Set_up_a_development_environment.md
docs/01_Development_How_To/03_Debugging.md
docs/01_Development_How_To/03_Updating_source_files.md
docs/01_Development_How_To/04_Debugging.md
docs/03_Plugin_System/05_Toast_Messages.md
docs/03_Plugin_System/06_Logging.md

I think now the docs will help others to get an easier step-by-step explanation when starting with development. Further I have added new section about toast messages and logging.

split up some parts and added toast message and logger explanation 

---

docs/01_Development_How_To/02_Set_up_a_development_environment.md

Align developer doc with feature from pull request #1295 "Volumio pull feature for branch and forked repository"

Align developer doc with feature from pull request #1295

---

docs/02_API/02_WebSocket_APIs.md

sorry for the merge commit - forgot to rebase 👎

added docu about favourites websocket api

---

docs/03_Plugin_System/02_Writing_A_Plugin.md

This includes 'make' which is needed for some npm packages.

Added the need for build-essential

---

docs/_index.md

Made several grammatical tweaks. Added a link to docs.v.o so it is easier
to go from viewing the sources on GH to the final published docs.

Updates to opening text on front page

---

docs/00_User_Manual/08_Sending_logs_for_troubleshooting.md

Use actual IP address rather than text

Clarification

---

docs/08_FAQs/03_Audio_Sources.md

I read the original words but did not get the full meaning until reading a comment in an issue. Perhaps this version is more approachable.

Longer explanation of INTERNAL folder

---

docs/00_User_Manual/00_Quick_Start_Guide.md

The main point is Volumio can do this so start with that.
Then explain how to set up HDMI for the various platforms.
Put the steps for the plugin as a sub-list under the plugin
option's dot point.

Rearrange the HDMI section

---

docs/00_User_Manual/00_Quick_Start_Guide.md

I actually installed the plugin on my rpi2 and that prompted a couple of extra changes. See what you think.

Further touch display tweaks

---

docs/00_User_Manual/01_First_steps_with_Volumio.md

This is all minor changes trying to make usage and wording more consistent, hopefully uncontroversial.

Rework of 'First steps with Volumio'

---

docs/00_User_Manual/04_Volume_Control_and_audio_quality.md

This and the following chapters each present quite small chunks of information, perhaps they should be merged into a larger chapter?

Tweaking wording and restructure a little

---

docs/00_User_Manual/05_Stream_audio_to_volumio.md

Seems like the troubleshooting part could use more suggestions but right now I can't think of anything that would be useful

Small tweaks to 'streaming' chapter

---

docs/02_API/02_WebSocket_APIs.md

I changed the docs to reflect how I was able to use the API.

Fixed removeFromQueue and addToQueue docs

---

docs/02_API/02_WebSocket_APIs.md

In my tests it doesn't work with "GetQueue", but with "getQueue", which may take some minutes to find out.

Fixed getQueue API docs

---

docs/03_Plugin_System/04_UI_Configuration_Pages.md

Fixes indentation and spelling in documentation

Refactor: fix indentation and spelling

---

docs/03_Plugin_System/05_Toast_Messages.md

Here https://github.com/volumio/Volumio2-UI/blob/462f1b8896ae27db7045e0c2d64a963ae4280d75/src/app/services/toast-message.service.js#L24 you can see that "alert" does not exist but that it's actually called "warning"

Corrected the types of toast messages

---

docs/01_Development_How_To/08_Helping_the_project.md

Not sure if this is the right place to put this, but here goes

Advice for 'peripheral' project helpers

---

docs/00_User_Manual/05_Stream_audio_to_volumio.md
docs/08_FAQs/03_Audio_Sources.md

- Added information to the NAS drive share section in docs/08_FAQs/03_Audio_Sources.md detailing connecting using a domain account
- Updated Bluetooth section in docs/08_FAQs/03_Audio_Sources.md to reference Bluetooth input functionality in MyVolumio
- Corrected typo in docs/00_User_Manual/05_Stream_audio_to_volumio.md.

Updated Audio Sources and Typo in Stream Audio to Volumio

---

docs/00_User_Manual/05_Stream_audio_to_volumio.md

Add swyh-rs as an option to stream audio to Volumio

---

docs/03_Plugin_System/02_Writing_A_Plugin.md

According to the discussion [over here](https://community.volumio.org/t/volumio-plugin-refresh-changes-to-index-js-are-not-seen-old-version-of-index-js-runs-solved-run-volumio-vrestart/44552/8) the PR adds a hint to the paragraph "volumio plugin refresh".

Addition to 02_Writing_A_Plugin.md regarding "volumio plugin refresh"

---

docs/00_User_Manual/06_SSH.md

Not 100% sure about replacing the screenshot with the actual text, see what you think.

Ssh page updates

---

docs/08_FAQs/03_Audio_Sources.md

This was requested in the 'documentation feedback' topic on the forums

Explain how to upload to the share

---

docs/08_FAQs/00_General.md

Typo in docs mimimum
